import { Inter } from 'next/font/google'
import './globals.css'
import DashboardLayout from '@/components/DashboardLayout'
import { ReduxProvider } from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <DashboardLayout />
            {children}
          </ReduxProvider>
      </body> 
    </html>
  )
}
